CONFIG_I2C=y
CONFIG_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_TROVATORE_DUAL_OLED_APP=y

# Use only custom dual OLED renderer to avoid conflicts with ZMK status widgets.
CONFIG_ZMK_DISPLAY=n

## Pointing
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y

## Debug & Logging
CONFIG_LOG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_ZMK_SLEEP=n


