CONFIG_I2C=y
CONFIG_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_TROVATORE_DUAL_OLED_APP=n

## Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_WPM=y

## Pointing
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y

## Debug & Logging
CONFIG_LOG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_ZMK_SLEEP=n

# 위젯 제어 (enable/disable)
CONFIG_ZMK_DONGLE_DISPLAY_BONGO_CAT=n      # bongo cat 위젯
CONFIG_ZMK_DONGLE_DISPLAY_MODIFIERS=y      # active modifiers
CONFIG_ZMK_DONGLE_DISPLAY_LAYER=y          # layer name
CONFIG_ZMK_DONGLE_DISPLAY_WPM=n            # WPM meter

# 세부 설정
CONFIG_ZMK_DONGLE_DISPLAY_LAYER_TEXT_ALIGN="left"
CONFIG_ZMK_DONGLE_DISPLAY_LAYER_NAME_SCROLL_WIDTH=50
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y
CONFIG_ZMK_DONGLE_DISPLAY_MAC_MODIFIERS=n

