## Split keyboards
## https://zmk.dev/docs/config/system#split-keyboards
# CONFIG_ZMK_SPLIT=y
# CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

## ZMK Studio
## https://zmk.dev/docs/features/studio
CONFIG_ZMK_STUDIO=y
## https://zmk.dev/docs/config/studio
CONFIG_ZMK_STUDIO_LOCKING=y
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=y
CONFIG_ZMK_STUDIO_TRANSPORT_BLE_PREF_LATENCY=5

## Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_WPM=y

# 위젯 제어 (enable/disable)
CONFIG_ZMK_DONGLE_DISPLAY_BONGO_CAT=n      # bongo cat 위젯
CONFIG_ZMK_DONGLE_DISPLAY_MODIFIERS=y      # active modifiers
CONFIG_ZMK_DONGLE_DISPLAY_LAYER=y          # layer name
CONFIG_ZMK_DONGLE_DISPLAY_WPM=n            # WPM meter

# 세부 설정
CONFIG_ZMK_DONGLE_DISPLAY_LAYER_TEXT_ALIGN="left"
CONFIG_ZMK_DONGLE_DISPLAY_LAYER_NAME_SCROLL_WIDTH=50
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y
CONFIG_ZMK_DONGLE_DISPLAY_MAC_MODIFIERS=n
